### ISSUE TITLE
Proxy support for Wordpress integration

### ISSUE THREAD

**Issue by jmunroe** [cioos-siooc/cioos-siooc-assetmap#29]
Determine how this asset map could be deployed as a plugin to a Word press environment.
- is any PHP required?
- are design changes needed to integrate with wordpress?
- need a working example of how this could work along with written instructions of the process of release a wordpress plugin.

**Comment by jmunroe** [comment]
I will ask @justhateme to work on this task. If there is already work started on this issue, please comment here so that we do not duplicate work.

If this task can be made more specific (especially based on discussion in the UX task team meeting next week, @GermainSauve @odumidika @fostermh) please provide direction here.

**Comment by jmunroe** [comment]
The team feels that this should be relatively straightforward. We'll push it for our January release.

**Comment by joelfriesen** [comment]
It may have something to do with this 

`ckan_server.ckan_proxy_name = 'ckan_instance.substring(0, ckan_instance.length - 5)'`

found in the asseet.js file -  If the proxy is undefined, this line still manages to insert something in here.

**Comment by sauve** [comment]
The asset map is now an independant web app and no more Wordpress integration is planned.
