### ISSUE TITLE
implement cluster mouse over / clic

### ISSUE THREAD

**Issue by jmunroe** [cioos-siooc/cioos-siooc-assetmap#3]

**Comment by jmunroe** [comment]
We need to implement the Click/Double-Click functionality of map elements. 

Is this related to #10 ?

**Comment by jmunroe** [comment]
Double click a cluster to zoom in to the extent of the feature member. Center on the centroid.

**Comment by sauve** [comment]
Click on cluster now list the clustered datasets in the dataset panels. No pan or zoom. Will require comment from users for the doubleclick feature.
