### ISSUE TITLE
map markers don't always reflect filters

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/cioos-siooc-assetmap#48]
To reproduce this bug, from the standalone app with default settings try clicking 'Temperature' and 'Vent' and then click them again to deselect all filters. The sidebar list goes to 0 but the points remain on the map. It seems to only happen with more than one EOV selected.

![Screen Shot 2019-11-29 at 11 34 33 AM](https://user-images.githubusercontent.com/26209011/69887531-46307380-129c-11ea-9907-9bc41879f4d0.png)

**Comment by sauve** [comment]
Was due to the recreation of the cluster map. The old one was still referenced by the map yet wasn't cleaned or updated by the filters. Removed the re-creation of the cluster map, update only the source and set the layer visibility to false if required.
