### ISSUE TITLE
old polygon should disappear when new point selected

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/cioos-siooc-assetmap#52]
I think the polygon should disappear when a new point is selected, otherwise it is confusing to have a polygon showing that is unrelated to the focussed dataset.

![Screen Shot 2019-12-02 at 3 33 47 PM](https://user-images.githubusercontent.com/26209011/70003809-2c4f9480-1519-11ea-915f-c3a2f9274d63.png)

**Comment by sauve** [comment]
The main brancj has simplified click support ( remove selectclick and doubleclick ). this ralways remove the coverage polygone if shown.
