### ISSUE TITLE
Looks like the Nitrate.svg icon file is missing on the national asset map

### ISSUE THREAD

**Issue by jacobthompson101** [cioos-siooc/cioos-siooc-assetmap#67]
Checked out the national asset map, looks great! Noticed the nitrate.svg icon is missing.
![nitrate_svg_missing](https://user-images.githubusercontent.com/28519105/75911850-97fe1200-5e26-11ea-805b-749785519d3a.png)

**Comment by jacobthompson101** [comment]
The error in Chrome dev tools.
nitrate.svg:1
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by sauve** [comment]
My bad, forgot to add the icons in the Wordpress national repo. This is fixed now.
